### ISSUE TITLE
Python errors on TrueNAS-SCALE-22.02-RC.2

### ISSUE THREAD

**Issue by xTITUSMAXIMUSX** [truecharts/truetool#3]
Command: `pip install --no-cache-dir --upgrade truetool && truetool -b -s -u -a -p`

**Output:**

Collecting truetool
Downloading truetool-3.0.3-py3-none-any.whl (6.1 kB)
Installing collected packages: truetool
Successfully installed truetool-3.0.3
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/midcli/command/call_mixin/__init__.py", line 37, in call
rv = c.call(name, *args, job=job, callback=self._job_callback)
File "/usr/lib/python3/dist-packages/midcli/command/call_mixin/__init__.py", line 37, in call
rv = c.call(name, *args, job=job, callback=self._job_callback)
File "/usr/lib/python3/dist-packages/middlewared/client/client.py", line 458, in call
raise CallTimeout("Call timeout")
middlewared.client.client.CallTimeout: Call timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/bin/cli", line 12, in <module>
sys.exit(main())
File "/usr/lib/python3/dist-packages/midcli/__main__.py", line 262, in main
cli.run()
File "/usr/lib/python3/dist-packages/midcli/__main__.py", line 176, in run
self.context.process_input(self.command)
File "/usr/lib/python3/dist-packages/midcli/context.py", line 309, in process_input
namespace = self.current_namespace.process_input(text)
File "/usr/lib/python3/dist-packages/midcli/context.py", line 78, in process_input
return i.process_input(rest)
File "/usr/lib/python3/dist-packages/midcli/context.py", line 78, in process_input
return i.process_input(rest)
File "/usr/lib/python3/dist-packages/midcli/context.py", line 81, in process_input
i.process_input(rest)
File "/usr/lib/python3/dist-packages/midcli/command/query/command.py", line 40, in process_input
self.call(self.method["name"], parsed.filters, parsed.options,
File "/usr/lib/python3/dist-packages/midcli/command/call_mixin/__init__.py", line 48, in call
if (error := self._handle_error(e)) is not None:
File "/usr/lib/python3/dist-packages/midcli/command/call_mixin/__init__.py", line 81, in _handle_error
if e.trace["class"] == "CallError":
TypeError: 'NoneType' object is not subscriptable
Starting TrueCharts TrueTool...

Cleaning old backups to a max. of 14...

Running App Backup...

[10%] Basic validation complete...

[36%] Backing up plex...

[63%] Backing up heimdall...

[90%] Backing up nessus...

[95%] Taking snapshot of ix-applications...

[100%] Backup 'TrueTool_2022_02_10_20_20_43' complete...

TrueTool_2022_02_10_20_20_43

Syncing Catalogs...

[0%] Syncing OFFICIAL catalog...

[50%] Syncing TRUECHARTS catalog...

[100%] Syncing TRUECHARTS catalog...

<null>

Executing Updates...

Pruning old docker images...

Images pruned.

TrueTool Finished

**Comment by Ornias1993** [comment]
could you try not doing an `&&`
It's hard to figure out when the errors is actually thrown.

**Comment by xTITUSMAXIMUSX** [comment]
Yeah sure thing.

command: `truetool -b -s -u -a -p`

**Output:**
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/midcli/command/call_mixin/__init__.py", line 37, in call
rv = c.call(name, *args, job=job, callback=self._job_callback)
File "/usr/lib/python3/dist-packages/midcli/command/call_mixin/__init__.py", line 37, in call
rv = c.call(name, *args, job=job, callback=self._job_callback)
File "/usr/lib/python3/dist-packages/middlewared/client/client.py", line 458, in call
raise CallTimeout("Call timeout")
middlewared.client.client.CallTimeout: Call timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/bin/cli", line 12, in <module>
sys.exit(main())
File "/usr/lib/python3/dist-packages/midcli/__main__.py", line 262, in main
cli.run()
File "/usr/lib/python3/dist-packages/midcli/__main__.py", line 176, in run
self.context.process_input(self.command)
File "/usr/lib/python3/dist-packages/midcli/context.py", line 309, in process_input
namespace = self.current_namespace.process_input(text)
File "/usr/lib/python3/dist-packages/midcli/context.py", line 78, in process_input
return i.process_input(rest)
File "/usr/lib/python3/dist-packages/midcli/context.py", line 78, in process_input
return i.process_input(rest)
File "/usr/lib/python3/dist-packages/midcli/context.py", line 81, in process_input
i.process_input(rest)
File "/usr/lib/python3/dist-packages/midcli/command/query/command.py", line 40, in process_input
self.call(self.method["name"], parsed.filters, parsed.options,
File "/usr/lib/python3/dist-packages/midcli/command/call_mixin/__init__.py", line 48, in call
if (error := self._handle_error(e)) is not None:
File "/usr/lib/python3/dist-packages/midcli/command/call_mixin/__init__.py", line 81, in _handle_error
if e.trace["class"] == "CallError":
TypeError: 'NoneType' object is not subscriptable
Starting TrueCharts TrueTool...

Cleaning old backups to a max. of 14...

Running App Backup...

[10%] Basic validation complete...

[30%] Backing up plex...

[50%] Backing up heimdall...

[70%] Backing up nessus...

[90%] Backing up librespeed...

[95%] Taking snapshot of ix-applications...

[100%] Backup 'TrueTool_2022_02_11_10_23_17' complete...

TrueTool_2022_02_11_10_23_17


Syncing Catalogs...

[0%] Syncing OFFICIAL catalog...

[50%] Syncing TRUECHARTS catalog...

[100%] Syncing TRUECHARTS catalog...

<null>


Executing Updates...

Pruning old docker images...

Images pruned.

TrueTool Finished

**Comment by Ornias1993** [comment]
This often happens when it tries to delete old backups of which the snapshots are already wiped...

**Comment by RickDB** [comment]
Cleaned up the truetools snapshots and indeed error disappeared.

**Comment by xTITUSMAXIMUSX** [comment]
What did you clean up exactly? This error showed up the first time I ever ran it.

**Comment by Ornias1993** [comment]
People, please wait for release of TrueNAS SCALE first and reopen if its still thr case.
